
title: Rahul's Homepage
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Rahul Handa
tagline: Software Developer | Budding Computer Scientist
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: rahulhanda123@gmail.com
phone: 413 552 9359
#website: blog.webjeda.com #do not add http://
linkedin: rahul-handa-8956a048
github: rahulhanda123
twitter: '@Rahulhanda90'


# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
